# Generated by Django 4.2.10 on 2026-06-06 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colab', '0002_ega_kpis_prod'),
    ]

    operations = [
        migrations.CreateModel(
            name='ITENS_260521',
            fields=[
                ('recid', models.IntegerField(primary_key=True, serialize=False)),
                ('os', models.BigIntegerField(null=True)),
                ('maquina', models.IntegerField(null=True)),
                ('sequencia', models.IntegerField(null=True)),
                ('operacao', models.IntegerField(null=True)),
                ('peca', models.IntegerField(null=True)),
                ('molde', models.IntegerField(null=True)),
                ('status', models.IntegerField(null=True)),
                ('programacao', models.DateTimeField(null=True)),
                ('modificacao', models.DateTimeField(null=True)),
                ('inicio', models.DateTimeField(blank=True, null=True)),
                ('final', models.DateTimeField(blank=True, null=True)),
                ('programado', models.IntegerField(null=True)),
                ('produzido', models.IntegerField(null=True)),
                ('rejeitado', models.IntegerField(null=True)),
                ('pecas_hora', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('production_order', models.BigIntegerField(null=True)),
                ('itens_prd', models.IntegerField(null=True)),
                ('itens_rej', models.IntegerField(null=True)),
                ('lim_entrega', models.DateTimeField(blank=True, null=True)),
                ('prev_inicio', models.DateTimeField(blank=True, null=True)),
                ('prev_entrega', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OEE_Prod_260521',
            fields=[
                ('recid', models.IntegerField(primary_key=True, serialize=False)),
                ('maquina', models.IntegerField(null=True)),
                ('inicio', models.DateTimeField(null=True)),
                ('os', models.BigIntegerField(null=True)),
                ('produto', models.IntegerField(null=True)),
                ('operacao', models.IntegerField(null=True)),
                ('molde', models.IntegerField(null=True)),
                ('ttotal', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('sec_total', models.IntegerField(null=True)),
                ('tdisp', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('sec_disp', models.IntegerField(null=True)),
                ('tprod', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('sec_prod', models.IntegerField(null=True)),
                ('qtde_std', models.IntegerField(null=True)),
                ('qtde_real', models.IntegerField(null=True)),
                ('qtde_boas', models.IntegerField(null=True)),
                ('teep', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('oee', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('disp', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('perf', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('qual', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='EGA_KPIS_PROD',
        ),
        migrations.DeleteModel(
            name='Teste',
        ),
    ]
