# Generated by Django 4.2.10 on 2026-06-11 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colab', '0003_itens_260521_oee_prod_260521_delete_ega_kpis_prod_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PRODUTOS_260610',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peca', models.IntegerField(null=True)),
                ('operacao', models.IntegerField(null=True)),
                ('codigo', models.CharField(max_length=100, null=True)),
                ('cavidades', models.IntegerField(null=True)),
                ('pecas_hora', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('molde', models.IntegerField(null=True)),
            ],
        ),
    ]
