# Generated by Django 4.2.10 on 2026-06-12 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colab', '0004_produtos_260610'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ITENS_260521',
            new_name='ITENS_260611',
        ),
        migrations.RenameModel(
            old_name='OEE_Prod_260521',
            new_name='OEE_Prod_260611',
        ),
    ]
