# Generated by Django 4.2.10 on 2026-06-13 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colab', '0005_rename_itens_260521_itens_260611_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ITENS_260611',
            new_name='ITENS_260612',
        ),
        migrations.RenameModel(
            old_name='OEE_Prod_260611',
            new_name='OEE_Prod_260612',
        ),
    ]
