# Generated by Django 4.2.10 on 2026-06-13 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colab', '0006_rename_itens_260611_itens_260612_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ITENS_260612',
            new_name='ITENS_260611',
        ),
        migrations.RenameModel(
            old_name='OEE_Prod_260612',
            new_name='OEE_Prod_260611',
        ),
    ]
